# Package Tracking Server Configuration (TOML)
# Copy this file to config.toml and configure as needed

[server]
host = "localhost"
port = 8080

[database]
path = "./database.db"

[logging]
level = "info"

[update]
interval = "1h"
auto_enabled = true
cutoff_days = 30
failure_threshold = 10
batch_size = 10
max_retries = 10
batch_timeout = "60s"
individual_timeout = "30s"

[carriers.usps]
api_key = ""  # Optional: your_usps_api_key

[carriers.ups]
client_id = ""        # your_ups_client_id
client_secret = ""    # your_ups_client_secret
api_key = ""          # deprecated - use OAuth2 instead
auto_update_enabled = true
auto_update_cutoff_days = 30

[carriers.fedex]
api_key = ""          # your_fedex_client_id
secret_key = ""       # your_fedex_client_secret
api_url = "https://apis.fedex.com"

[carriers.dhl]
api_key = ""          # your_dhl_api_key
auto_update_enabled = true
auto_update_cutoff_days = 0

[cache]
ttl = "5m"
disabled = false

[rate_limit]
disabled = false

[admin]
api_key = ""           # your_secret_admin_api_key_here
auth_disabled = false  # Set to true to disable authentication for development